services:
  game:
    restart: on-failure
    image: golem:latest
    ports:
      - "4000:4000"
      - "40000:40000"
      - "6060:6060"
      - "9000:9000"
    volumes:
      - ./etc:/app/etc
      - ./migrations:/app/migrations
      - ./scripts:/app/scripts
