version: "3.9"
    
services:
  mysql:
    image: mysql:8.0
    networks:
      - overlay
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
  game:
    depends_on:
      - mysql
    image: golem:latest
    networks:
      - overlay
    ports:
      - "4000:4000"
    restart: "always"
    volumes:
      - ./etc:/etc/golem

networks:
  overlay:

volumes:
  db_data: {}
  etc: