version: "3.9"
    
services:
  redis:
    image: redislabs/redisgears:latest
    networks:
      - overlay
    ports:
      - 6379:6379
  mysql:
    image: mysql:8.0
    networks:
      - overlay
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    networks:
      - overlay
    ports:
      - 8000:80
    environment:
      - 'PMA_HOST=mysql'
      - 'PMA_USER=root'
      - 'PMA_PASSWORD=rootpassword'
      - 'PMA_PORT=3306'
  game:
    depends_on:
      - mysql
    restart: on-failure
    image: golem:latest
    networks:
      - overlay
    ports:
      - "4000:4000"
      - "40000:40000"
      - "6060:6060"
      - "9000:9000"
    volumes:
      - ./etc:/app/etc
      - ./scripts:/app/scripts

networks:
  overlay:

volumes:
  db_data: {}
  etc: